name: ServerUtils
version: 3.5.5-SNAPSHOT
main: net.frankheijden.serverutils.bukkit.ServerUtils
description: A server utility
authors:
 - FrankHeijden
website: https://github.com/FrankHeijden/ServerUtils
folia-supported: true
api-version: 1.13
softdepend:
 - ServerUtilsUpdater
