name: Java CI with Gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ matrix.java-version }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew clean build --stacktrace
    - name: Upload artififacts
      uses: actions/upload-artifact@v2.2.1
      with:
        name: ServerUtils
        path: jars/*.jar
    - name: Publish
      if: ${{ github.event_name == 'push' }}
      env:
        FVDH_USERNAME: ${{ secrets.FVDH_USERNAME }}
        FVDH_TOKEN: ${{ secrets.FVDH_TOKEN }}
      run: ./gradlew publish --stacktrace
